import type { TherapeuticContent, Session } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const getImage = (id: string) => {
  const img = PlaceHolderImages.find(p => p.id === id);
  return {
    url: img?.imageUrl || 'https://picsum.photos/seed/placeholder/600/400',
    hint: img?.imageHint || 'placeholder',
  };
};

export const therapeuticContent: TherapeuticContent[] = [
  {
    id: '1',
    category: 'Mobile Apps',
    title: 'Mindful Moments',
    description: 'A calming app for guided meditation and mindfulness exercises. Designed to gently occupy the mind.',
    thumbnailUrl: getImage('therapy-app-1').url,
    imageHint: getImage('therapy-app-1').hint,
    platform: ['iOS', 'Android'],
    duration: '5-20 min sessions',
    rating: 4.8,
    intensity: 'Low',
    accessibility: ['Screen Reader Friendly'],
  },
  {
    id: '2',
    category: 'VR Experiences',
    title: 'Serene Forest Walk',
    description: 'Immerse yourself in a peaceful forest environment. No sudden sounds or startling visuals.',
    thumbnailUrl: getImage('therapy-vr-1').url,
    imageHint: getImage('therapy-vr-1').hint,
    platform: ['VR Headset'],
    duration: '15-30 min',
    rating: 4.9,
    intensity: 'Low',
    accessibility: ['Reduced Motion'],
  },
  {
    id: '3',
    category: 'AI-Guided Exercises',
    title: 'Cognitive Flow',
    description: 'Engage in pattern-based cognitive exercises guided by a gentle AI. Helps improve focus.',
    thumbnailUrl: getImage('therapy-exercise-1').url,
    imageHint: getImage('therapy-exercise-1').hint,
    platform: ['Web'],
    duration: '10 min exercises',
    rating: 4.7,
    intensity: 'Moderate',
    accessibility: ['Colorblind Mode'],
  },
  {
    id: '4',
    category: 'Ambient Soundscapes',
    title: 'Ocean Breath',
    description: 'Listen to the soothing sounds of ocean waves to promote relaxation and sleep.',
    thumbnailUrl: getImage('therapy-sound-1').url,
    imageHint: getImage('therapy-sound-1').hint,
    platform: ['Web', 'iOS', 'Android'],
    duration: 'Continuous loop',
    rating: 4.9,
    intensity: 'Low',
    accessibility: [],
  },
  {
    id: '5',
    category: 'Mobile Apps',
    title: 'Pattern Weave',
    description: 'Gently create beautiful, intricate patterns with your fingertips. A quiet, focused activity.',
    thumbnailUrl: getImage('therapy-app-2').url,
    imageHint: getImage('therapy-app-2').hint,
    platform: ['iOS', 'Android'],
    duration: 'Self-paced',
    rating: 4.6,
    intensity: 'Low',
    accessibility: ['Reduced Motion'],
  },
  {
    id: '6',
    category: 'VR Experiences',
    title: 'StarSailor',
    description: 'Float through a calm, beautiful galaxy at your own pace. A visually soothing journey.',
    thumbnailUrl: getImage('therapy-vr-2').url,
    imageHint: getImage('therapy-vr-2').hint,
    platform: ['VR Headset'],
    duration: '20 min journey',
    rating: 4.8,
    intensity: 'Moderate',
    accessibility: ['Reduced Motion'],
  },
  {
    id: '7',
    category: 'AI-Guided Exercises',
    title: 'Mindful Breathing Companion',
    description: 'An AI companion guides you through paced breathing exercises to calm the nervous system.',
    thumbnailUrl: getImage('therapy-exercise-2').url,
    imageHint: getImage('therapy-exercise-2').hint,
    platform: ['Web'],
    duration: '5 min sessions',
    rating: 4.9,
    intensity: 'Low',
    accessibility: ['Screen Reader Friendly'],
  },
  {
    id: '8',
    category: 'Ambient Soundscapes',
    title: 'Night Forest',
    description: 'The gentle, ambient sounds of a forest at night, including crickets and a soft breeze.',
    thumbnailUrl: getImage('therapy-sound-2').url,
    imageHint: getImage('therapy-sound-2').hint,
    platform: ['Web', 'iOS', 'Android'],
    duration: 'Continuous loop',
    rating: 4.8,
    intensity: 'Low',
    accessibility: [],
  },
];

export const sessionHistory: Session[] = [
  { id: '1', date: '2024-06-15', prediction: 'negative', confidence: 0.92, processingTime: 45321 },
  { id: '2', date: '2024-07-01', prediction: 'negative', confidence: 0.88, processingTime: 47123 },
  { id: '3', date: '2024-07-20', prediction: 'positive', confidence: 0.65, processingTime: 46543 },
  { id: '4', date: '2024-08-10', prediction: 'negative', confidence: 0.95, processingTime: 44987 },
];
